// Generated by CoffeeScript 1.6.2
(function() {
  var type, _fn, _i, _len, _ref;

  _ref = ['click', 'dblclick', 'focusout', 'hover', 'mousedown', 'mouseenter', 'mouseleave', 'mousemove', 'mouseout', 'mouseover', 'mouseup'];
  _fn = function() {
    var handle, special;

    special = $.event.special[type];
    if (special == null) {
      special = $.event.special[type] = {};
    }
    handle = special.handle;
    return $.extend(special, {
      handle: function(_arg) {
        var enabled, handler, target, _ref1;

        (_ref1 = _arg.handleObj, handler = _ref1.handler), target = _arg.target;
        enabled = $.data(target).enabled;
        if (enabled === false) {
          return;
        }
        if (handle != null) {
          return handle.apply(this, arguments);
        } else {
          return handler.apply(this, arguments);
        }
      }
    });
  };
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    type = _ref[_i];
    _fn();
  }

  $.fn.extend({
    enabled: function(value) {
      var data, el, _j, _len1, _ref1, _ref2;

      for (_j = 0, _len1 = this.length; _j < _len1; _j++) {
        el = this[_j];
        data = $.data(el);
        if (value == null) {
          return (_ref1 = data.enabled) != null ? _ref1 : true;
        }
        if (data.enabled !== value) {
          data.enabled = value;
          if ((_ref2 = data.button) != null) {
            _ref2.updateEnabled();
          }
        }
      }
      return this;
    }
  });

}).call(this);

/*
//@ sourceMappingURL=jquery.enabled.map
*/
